name: Deploy goals API

on:
  workflow_dispatch:

jobs:
  pipeline:
    uses: IDEMSInternational/parenttext-goals-webhooks/.github/workflows/deploy.yml@c0d4d7d32236d4ad4a68cf1b07a552b53af8a360
    secrets:
      credentials: ${{ secrets.GCP_CREDENTIALS }}
    with:
      image: ${{ vars.GOALS_API_IMAGE }}
      region: ${{ vars.GCP_REGION }}
      service_env: ${{ vars.GCP_SERVICE_ENV }}
      service_identity: ${{ vars.GCP_SERVICE_IDENTITY }}
      service_name: ${{ vars.GCP_SERVICE_NAME }}
